### PR TITLE
Add infeasibility certificates

### PR DESCRIPTION
**Pull request by rafabench**
Solved issue https://github.com/JuliaOpt/Xpress.jl/issues/54

### CODE REVIEW

**Comment by joaquimg** [comment]
@jd-lara travis will only work for branches in the main Repo?
PRs from forks won't work?

**Comment by jd-lara** [comment]
No CI allows access to secret values from fork PR's

**Comment by joaquimg** [comment]
If it should work I dont understand the fail.

**Comment by joaquimg** [comment]
replaced by #65

**Pull request closed without merging**
