### PR TITLE
update testing code

### PR DESCRIPTION
**Pull request by jd-lara**
This PR updates the test code and removes old files.

### CODE REVIEW

**Comment by jd-lara** [comment]
Current status: 

The enables tests are failing consistently because of an array + value operation. 

```Julia
Got exception outside of a @test
  MethodError: no method matching -(::Array{Int64,1}, ::Int64)
  Closest candidates are:
    -(!Matched::Complex{Bool}, ::Real) at complex.jl:299
    -(!Matched::Missing, ::Number) at missing.jl:94
    -(!Matched::Base.CoreLogging.LogLevel, ::Integer) at logging.jl:107
    ...
  Stacktrace:
   [1] addcols(::Xpress.XpressProblem, ::Array{Float64,1}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/jdlara/Dropbox/Code/Xpress.jl/src/api.jl:4803
   [2] add_variable(::Xpress.Optimizer) at /Users/jdlara/Dropbox/Code/Xpress.jl/src/MOI/MOI_Wrapper.jl:463
   [3] add_variable(::MathOptInterface.Bridges.LazyBridgeOptimizer{Xpress.Optimizer}) at /Users/jdlara/.julia/packages/MathOptInterface/A2UPd/src/Bridges/bridge_optimizer.jl:1128
```

**Comment by joaquimg** [comment]
nice updates.
About the error...
I would start testing:
```julia
# create prob
inner = XpressProblem()
# add one variable
Xpress.addcols(inner,
                    [0.0],#_dobj::Vector{Float64},
                    Int[],#_mstart::Vector{Int},
                    Int[],#_mrwind::Vector{Int},
                    Float64[],#_dmatval::Vector{Float64},
                    [-Inf],#_dbdl::Vector{Float64},
                    [Inf],#_dbdu::Vector{Float64}
                    )

```

**Comment by jd-lara** [comment]
@joaquimg just as a reference => same result 

```
julia> m = Xpress.Optimizer()
Xpress Problem:
    type   : LP
    sense  : minimize
    number of variables                    = 0
    number of linear constraints           = 0
    number of quadratic constraints        = 0
    number of sos constraints              = 0
    number of non-zero coeffs              = 0
    number of non-zero qp objective terms  = 0
    number of non-zero qp constraint terms = 0
    number of integer entities             = 0

julia> Xpress.addcols(m.inner,
                           [0.0],#_dobj::Vector{Float64},
                           Int[],#_mstart::Vector{Int},
                           Int[],#_mrwind::Vector{Int},
                           Float64[],#_dmatval::Vector{Float64},
                           [-Inf],#_dbdl::Vector{Float64},
                           [Inf],#_dbdu::Vector{Float64}
                           )
_mstart = Int64[]
?91 Error: No problem has been input
ERROR: XpressError(32): Subroutine not completed successfully, possibly due to invalid argument. Unable to call addcols
Stacktrace:
 [1] macro expansion at /Users/jdlara/Dropbox/Code/Xpress.jl/src/utils.jl:98 [inlined]
 [2] addcols(::Xpress.XpressProblem, ::Array{Float64,1}, ::Array{Int64,1}, ::Array{Int64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at /Users/jdlara/Dropbox/Code/Xpress.jl/src/api.jl:4806
 [3] top-level scope at REPL[9]:1
```

**Comment by kdheepak** [comment]
The Xpress APi is saying that there's some error in the arguments. Technically, the C API just returns `32`, and in `api.jl` I'm raising an error if the output return int is not zero. The Xpress library is printing "?91 Error: No problem has been input". I think some other function needs to be called before `addcols` can be called or the arguments are incorrect.

I'm looking into this right now.

**Comment by kdheepak** [comment]
[From Xpress documentation](https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/chapter9_sec_section9001.html):

> **91   No problem has been input.**
>    An operation has been attempted that requires a problem to have been input. Please make sure that XPRSreadprob (READPROB) is called and that the problem has been loaded successfully before trying again.

`readprob` only allows reading from a file though. This made be guess that something like `readprob` was needed before calling `addcols`. 

The related topics section in the documentation of `readprob` has the following section:

> XPRSloadglobal, XPRSloadlp, XPRSloadqglobal, XPRSloadqp. 

I tried `loadlp` and it seems to work:

Screen Shot 2019-11-11 at 2 03 31 PM

**Comment by joaquimg** [comment]
> The question is should this be added to the constructor of Xpress.XpressProblem?

No. You can see that its not needed in the old interface.

**Comment by joaquimg** [comment]
Actually YES,
this is called in the old inteface:
```julia
function load_empty(model::Model)
#=int XPRS_CC XPRSloadlp(XPRSprob prob, const char *probname, int ncol, int
      nrow, const char qrtype[], const double rhs[], const double range[],
      const double obj[], const int mstart[], const int mnel[], const int
      mrwind[], const double dmatval[], const double dlb[], const double
      dub[]);
=#
    ret = @xprs_ccall(loadlp, Cint,
        (Ptr{Nothing},
            Ptr{UInt8},
            Cint,
            Cint,
            Ptr{Cchar},#type
            Ptr{Float64},#rhs
            Ptr{Float64},#range
            Ptr{Float64},#obj
            Ptr{Cint},#mastart
            Ptr{Cint},#mnel
            Ptr{Cint},#mrwind
            Ptr{Float64},#dmat
            Ptr{Float64},#lb
            Ptr{Float64}#ub
            ),model.ptr_model,"",0,0,Cchar[],Float64[],Float64[],Float64[],
                Cint[],Cint[],Cint[],Float64[],Float64[],Float64[]
    )
    if ret != 0
        throw(XpressError(model))
    end
    nothing
end
```

**Comment by jd-lara** [comment]
@joaquimg It seems better to use XPRSloadglobal 

https://www.fico.com/fico-xpress-optimization/docs/latest/solver/optimizer/HTML/XPRSloadglobal.html

**Comment by joaquimg** [comment]
its all the same because we will initialize an empty one.

**Comment by jd-lara** [comment]
> its all the same because we will initialize an empty one.

Can you add QP's or Integers to a problem initialized as an LP?

**Comment by joaquimg** [comment]
yep

**Pull request merged**
