### PR TITLE
Fix maxtime crash.

### PR DESCRIPTION
**Pull request by hellemo**
I experienced crashes when xpress was interrupted when the time limit was reached. This attempts to fix the issue.

### CODE REVIEW

**Comment by joaquimg** [comment]
Nice!
Would it be possible to have a test?
Maybe a very simple problem with a very very small time limit.

**Comment by hellemo** [comment]
Yes, I actually thought about it, but the toy problems I had around solved way too fast, might have anohter look.

**Comment by joaquimg** [comment]
If its hard to find such an instance, no problem we can merge as is. Its looking good. let me know

**Comment by hellemo** [comment]
Sorry, haven't found the time, and probably won't in the next few weeks. Should be able to add it later.

**Comment by hellemo** [comment]
I added tests for MAXTIME, but it fails when trying to get rhs = XPR.get_rhs(instance.inner) in function LQOI.get_linear_primal_solution!(instance::Optimizer, place), and I haven't been able to figure out what to do about it.

**Pull request merged**
